- name: installing nginx
  hosts: prod
  become: yes


  tasks:

    - name: copy script
      copy:
        src: install.sh
        dest: /home/ubuntu/
        mode: '755'

    - name: run script
      command: /home/ubuntu/install.sh